export const dataSong = [
  {
    id: 1,
    name: "chill-1",
    src: "https://audio.jukehost.co.uk/txtXCJroBTDCwn17DVN5vWkJjDHqqkao",
    list: "chill",
  },
  {
    id: 2,
    name: "chill-2",
    src: "https://audio.jukehost.co.uk/klN2kDBpWGbWcpDvIXApOkJJlWtL4ERB",
    list: "chill",
  },
  {
    id: 3,
    name: "chill-3",
    src: "https://audio.jukehost.co.uk/PNY34a7rgD89zCmQO7riiLAz9Vlh1d7s",
    list: "chill",
  },
  {
    id: 4,
    name: "chill-4",
    src: "https://audio.jukehost.co.uk/QHvdk32UCbOi6mGQpUIV9cqfBvFxWmJZ",
    list: "chill",
  },
  {
    id: 5,
    name: "chill-5",
    src: "https://audio.jukehost.co.uk/EEYI5tPgLLCHM7g80S5CetFh87TmSY0x",
    list: "",
  },
  {
    id: 6,
    name: "chill-6",
    src: "https://audio.jukehost.co.uk/abu2sr9SITokIZfHXF4auLCZ7qG3xiiD",
    list: "chill",
  },
  {
    id: 10,
    name: "chill-10",
    src: "https://audio.jukehost.co.uk/wYkzp5203OS7zj1ii8zVZYTRKP11hwGa",
    list: "chill",
  },
  {
    id: 7,
    name: "chill-7",
    src: "https://audio.jukehost.co.uk/CMObO9pvO4cR7wxBKZFDTzY1LQW6szGs",
    list: "chill",
  },
  {
    id: 8,
    name: "chill-8",
    src: "https://audio.jukehost.co.uk/Eetsv6A277goEteQVzODUhxnWOVOUovz",
    list: "chill",
  },
  {
    id: 9,
    name: "chill-9",
    src: "https://audio.jukehost.co.uk/yZ6WdV0ZyKBQYrgVv0yUcbFZI5GdiDHq",
    list: "chill-9",
  },
  {
    id: 11,
    name: "jazz-1",
    src: "https://audio.jukehost.co.uk/YSs3m3JIKqLxjmRt3aQfOVbCUEHzcwOT",
    list: "jazz",
  },
  {
    id: 12,
    name: "jazz-2",
    src: "https://audio.jukehost.co.uk/wXXq1b8ZXg3ZwazmjMQUBuvUSWEvSpxz",
    list: "jazz",
  },
  {
    id: 13,
    name: "jazz-3",
    src: "https://audio.jukehost.co.uk/peTtbpWkFemOXe5gcPgA5laYtMWIujeM",
    list: "jazz",
  },
  {
    id: 14,
    name: "jazz-4",
    src: "https://audio.jukehost.co.uk/WC7LAjHV24JY51xa3R0qEUVfLDfxEWTL",
    list: "jazz",
  },
  {
    id: 15,
    name: "jazz-5",
    src: "https://audio.jukehost.co.uk/WFyBpM1bMVhg5GZNOABy0FUMa0AeqsH2",
    list: "jazz",
  },
  {
    id: 16,
    name: "jazz-6",
    src: "https://audio.jukehost.co.uk/CQ63pRtgIx4SvTqnZyNCnuHc0yiN8Iar",
    list: "jazz",
  },
  {
    id: 17,
    name: "jazz-7",
    src: "https://audio.jukehost.co.uk/OITr3SgxFYHxRSEUjbnjGSg6f7MeY9kr",
    list: "jazz",
  },
  {
    id: 18,
    name: "jazz-8",
    src: "https://audio.jukehost.co.uk/MidDbgl9dHEDbrTNQKGYDwietKvzjswm",
    list: "jazz",
  },
  {
    id: 19,
    name: "jazz-9",
    src: "https://audio.jukehost.co.uk/kasBQleZO1PD6RWQFZVf03W7Zf6deIFW",
    list: "jazz",
  },
  {
    id: 20,
    name: "jazz-10",
    src: "https://audio.jukehost.co.uk/zNLLu6JCaYR1Pc5THx8AM1iAenUMgt2c",
    list: "jazz",
  },
  {
    id: 21,
    name: "sleepy-1",
    src: "https://audio.jukehost.co.uk/gBvhzjsp1QYdzfjYc0ffyjwctCiv3ubs",
    list: "sleepy",
  },
  {
    id: 22,
    name: "sleepy-2",
    src: "https://audio.jukehost.co.uk/ZDb5OY2LBPnCQbab8s5mzU7iqvyENOIf",
    list: "sleepy",
  },
  {
    id: 23,
    name: "sleepy-3",
    src: "https://audio.jukehost.co.uk/7kHgTOQgVfN9TSaO8ME5KmE7nHkNUcgP",
    list: "sleepy",
  },
  {
    id: 24,
    name: "sleepy-4",
    src: "https://audio.jukehost.co.uk/uM7iXkhtrB3heGD4oA7624v8vZF9Lebl",
    list: "sleepy",
  },
  {
    id: 25,
    name: "sleepy-5",
    src: "https://audio.jukehost.co.uk/JjZjq9uSIriSTYs8ZCxiR3JxVvVTEeT0",
    list: "sleepy",
  },
  {
    id: 26,
    name: "sleepy-6",
    src: "https://audio.jukehost.co.uk/wKfypxlTXUOuKWp2Li1uYAh7cd5HkNUE",
    list: "sleepy",
  },
  {
    id: 27,
    name: "sleepy-7",
    src: "https://audio.jukehost.co.uk/j8BnVIvBelcdk8yDQMdW9zSyGf42B5UT",
    list: "sleepy",
  },
  {
    id: 28,
    name: "sleepy-8",
    src: "https://audio.jukehost.co.uk/FCkGZDE1twRTvwqf4eXadHGWIL2XvgWz",
    list: "sleepy",
  },
  {
    id: 29,
    name: "sleepy-9",
    src: "https://audio.jukehost.co.uk/gMCJDZb1NaRXTakvDOGXMR8NNSVJOKc6",
    list: "sleepy",
  },
  {
    id: 30,
    name: "sleepy-10",
    src: "https://audio.jukehost.co.uk/uu9jZzSO9ptbS4VFdnDajtPXfk1n2e9z",
    list: "sleepy",
  },
];
